---
- name: Add Deadsnakes PPA (Ubuntu)
  template: src=deadsnakes-ppa.list dest=/etc/apt/sources.list.d/deadsnakes-ppa.list mode=0644
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "trusty"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Deadsnakes Python 3.7 (Ubuntu)
  apt:
    state: latest
    name:
      - python3.7
      - python3.7-venv
      - python3.7-doc
      - python3.7-dev
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "trusty"

#- name: Install Deadsnakes pip 3.7 (Ubuntu)
#  command:
#    cmd: python3.7 -m ensurepip
#    creates: /usr/local/lib/python3.7/dist-packages/pip
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "trusty"

- name: Install basic tools
  apt:
    state: latest
    name:
      - autossh
      - bash-completion
      - bc
      - bind9-host
      - bzip2
      - cfv
      - colordiff
      - coreutils
      - curl
      - gawk
      - genisoimage
      - git
      - haveged
      - htop
      - httpie
      - inxi
      - iotop
      - lftp
      - links
      - lnav
      - lsb-release
      - lsof
      - mailutils
      - mediainfo
      - mkvtoolnix
      - ncdu
      - p7zip-full
      - procps
      - psmisc
      - python-virtualenv
      - sysstat
      - tmux
      - unzip
      - vim
      - virtualenvwrapper
      - vnstat
      - wget
      - zip

- name: Install newer Ubuntu packages
  apt:
    state: latest
    name:
      - python-packaging
  when: ansible_distribution_release in ("xenial", "bionic")

- name: Install ffmpeg
  apt: name=ffmpeg state=latest
  when: av_tool == 'ffmpeg' or ansible_distribution_release in ("precise", "bionic")

- name: Install libav
  apt: name=libav-tools state=latest
  when: av_tool == 'libav' or ansible_distribution_release not in ("precise", "bionic")

- name: Install fuseiso9660 + unrar (most distros)
  apt:
    state: latest
    name:
      - fuseiso9660
      - unrar-free
  when: not(ansible_distribution == "Debian") or not(ansible_distribution_major_version in "789")

- name: Install fuseiso + unrar-free (Wheezy, Jessie, Stretch)
  apt:
    state: latest
    name:
      # TODO: check what name to use for what distro/version (it's a mess)
      #- fuseiso
      #- fuseiso9660
      - unrar-free
  when: ansible_distribution == "Debian" and ansible_distribution_major_version in "789"

- name: Create local/lib directory
  file: path=/usr/local/lib/pmb state=directory owner=root group=root mode=0755

- name: Copy bash helper files
  copy: src={{ item }} dest=/usr/local/lib/pmb/{{ item }} owner=root group=root mode=0644
  with_items:
    - common.sh
