---
- name: Install basic tools
  apt: name={{ item }} state=latest
  with_items:
    - autossh
    - bash-completion
    - bc
    - bind9-host
    - bzip2
    - cfv
    - colordiff
    - curl
    - gawk
    - genisoimage
    - git
    - haveged
    - htop
    - httpie
    - iotop
    - lftp
    - links
    - lsb-release
    - lsof
    - mailutils
    - mediainfo
    - mkvtoolnix
    - ncdu
    - p7zip-full
    - psmisc
    - python-virtualenv
    - realpath
    - sysstat
    - tmux
    - unzip
    - vim
    - virtualenvwrapper
    - vnstat
    - wget
    - zip

- name: Install ffmpeg
  apt: name=ffmpeg state=latest
  when: av_tool == 'ffmpeg' or ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12"

- name: Install libav
  apt: name=libav-tools state=latest
  when: av_tool == 'libav' or not(ansible_distribution == "Ubuntu") or ansible_distribution_major_version != "12"

- name: Install fuseiso9660 + unrar (most distros)
  apt: name={{ item }} state=latest
  when: not(ansible_distribution == "Debian") or not(ansible_distribution_major_version in "789")
  with_items:
    - fuseiso9660
    - unrar

- name: Install fuseiso + unrar-free (Wheezy, Jessie, Stretch)
  apt: name={{ item }} state=latest
  when: ansible_distribution == "Debian" and ansible_distribution_major_version in "789"
  with_items:
    # TODO: check what name to use for what distro/version (it's a mess)
    #- fuseiso
    #- fuseiso9660
    - unrar-free

- name: Create local/lib directory
  file: path=/usr/local/lib/pmb state=directory owner=root group=root mode=0755

- name: Copy bash helper files
  copy: src={{ item }} dest=/usr/local/lib/pmb/{{ item }} owner=root group=root mode=0644
  with_items:
    - common.sh
